# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "rod-avg"
client_id = "8556c4a4d9a0c40e042e4e9ca12777aa"
application_url = "https://cbs-amp-yarn-protective.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://cbs-amp-yarn-protective.trycloudflare.com/auth/callback",
  "https://cbs-amp-yarn-protective.trycloudflare.com/auth/shopify/callback",
  "https://cbs-amp-yarn-protective.trycloudflare.com/api/auth/callback",
  "https://cbs-amp-yarn-protective.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "skincareavg.myshopify.com"
